default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 1234567890
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: real_me_api_development

test:
  <<: *default
  database: real_me_api_test

#
staging:
  <<: *default
  database: realme_api_staging
  username: <%= ENV['REALME_API_DATABASE_USERNAME'] %>
  password: <%= ENV['REALME_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['REALME_API_DATABASE_HOST'] %>

production:
  <<: *default
  database: realme_api_production
  username: <%= ENV['REALME_API_DATABASE_USERNAME'] %>
  password: <%= ENV['REALME_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['REALME_API_DATABASE_HOST'] %>