default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: admin
  host: localhost


development:
  <<: *default
  database: realme_api_staging
  username: <%= ENV['REALME_API_DATABASE_USERNAME'] %>
  password: <%= ENV['REALME_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['REALME_API_DATABASE_HOST'] %>

test:
  <<: *default
  database: realme_api_test

#
staging:
  <<: *default
  database: realme_api_staging
  username: <%= ENV['REALME_API_DATABASE_USERNAME'] %>
  password: <%= ENV['REALME_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['REALME_API_DATABASE_HOST'] %>

production:
  <<: *default
  database: realme_api_production
  username: <%= ENV['REALME_API_DATABASE_USERNAME'] %>
  password: <%= ENV['REALME_API_DATABASE_PASSWORD'] %>
  host: <%= ENV['REALME_API_DATABASE_HOST'] %>